# Generated by Django 5.1.3 on 2024-11-28 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('senha', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Combatente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nivel', models.PositiveIntegerField()),
                ('classe', models.CharField(max_length=100)),
                ('familia', models.CharField(max_length=100)),
                ('vida', models.PositiveIntegerField()),
                ('armadura', models.PositiveIntegerField()),
                ('iniciativa', models.PositiveIntegerField()),
                ('spell_slots', models.PositiveIntegerField()),
                ('prof_armas', models.PositiveIntegerField()),
                ('prof_magica', models.PositiveIntegerField()),
                ('tamanho', models.PositiveIntegerField()),
                ('traits', models.CharField(max_length=100)),
                ('incluir_gerativo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Encontro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('fim', models.DateField()),
                ('historico_turnos', models.TextField()),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servant_rpg_back.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='CombatenteGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrada_grupo', models.DateField()),
                ('saida_grupo', models.DateField()),
                ('combatente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servant_rpg_back.combatente')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servant_rpg_back.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='InimigoEncontro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combatente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servant_rpg_back.combatente')),
                ('encontro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servant_rpg_back.encontro')),
            ],
        ),
    ]
